## Linear algebra

# Matrix

In [1]:
import numpy as np
# create a 2x2 matrix
# np.array([[1,2,3,6,5],
#           [0,2,5,6,9]])
matrix1 = np.array([[1, 3], 
                   [5, 7]])

print("2x2 Matrix:\n",matrix1)

2x2 Matrix:
 [[1 3]
 [5 7]]


In [2]:
# create a 3x3  matrix
matrix2 = np.array([[2, 3, 5],
                    [7, 14, 21],
                    [1, 3, 5]])
                    
print("\n3x3 Matrix:\n",matrix2)


3x3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


# Diagonal Matrix

In [5]:
# diagonal matrix
from numpy import array
from numpy import diag
M = array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(M)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [6]:
# extract diagonal vector
d = diag(M)
print(d)
print()
# create diagonal matrix from vector
D = diag(d)
print(D)

[1 2 3]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Idendity matrix

In [8]:
# identity matrix
from numpy import identity
I = identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Matrix multiplication or Dot product

In [13]:
# create two matrices
matrix1 = np.array([[1, 3], [5, 7]])
             
matrix2 = np.array([[2, 6], 
                    [4, 8]])

# calculate the dot product of the two matrices
result = np.multiply(matrix1, matrix2)
print("multiplication of vectors \n",result)

result1 = np.dot(matrix1, matrix2)
print("matrix1 x matrix2: \n",result1)


multiplication of vectors 
 [[ 2 18]
 [20 56]]
matrix1 x matrix2: 
 [[14 30]
 [38 86]]


# matrix-vector multiplication

In [16]:
# matrix-vector multiplication
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
# print(A)
B = array([0.5, 0.5])
# print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[1.5 3.5 5.5]
[1.5 3.5 5.5]


In [17]:
import numpy as np
array1 = np.array([[1, 3], 
                   [5, 7]])
array2 = np.array([[2, 4], 
                   [6, 8]])
# inner() for 2D arrays
result = np.inner(array1, array2)
print(result)

[[14 30]
 [38 86]]


In [18]:
# outer() to perform outer multiplication
result = np.outer(array1, array2)
print(result)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [19]:
import numpy as np
# define the coefficient matrix A
A = np.array([[2, 4], 
             [6, 8]])
# define the constant vector b
b = np.array([5, 6])
# solve the system of linear equations Ax = b
x = np.linalg.solve(A, b)
print(x)

[-2.    2.25]


# transpose of metrix

In [24]:
# create a matrix
matrix1 = np.array([[1, 3], [5, 7]])

# get transpose of matrix1
result = np.transpose(matrix1)
result_1 = matrix1.T

print(result)
print(result_1)


[[1 5]
 [3 7]]
[[1 5]
 [3 7]]


In [25]:
inv_m = np.linalg.inv(result)
inv_m

array([[-0.875,  0.625],
       [ 0.375, -0.125]])

# inverse of matrix

In [21]:
#create a 3x3 square matrix
matrix1 = np.array([[1, 3, 5], 
                    [7, 9, 2],
                    [4, 6, 8]])

#find inverse of matrix1
result = np.linalg.inv(matrix1)
print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


# trace of matrix

In [26]:
from numpy import trace
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(A)
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [ ]:
# Determinant of matrix

In [27]:
# create a matrix
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 1],
                    [2, 3, 4]])
# find determinant of matrix1
result = np.linalg.det(matrix1)
print(result)

-4.999999999999999


In [ ]:
# Rank of determinant

In [28]:
from numpy.linalg import matrix_rank
# rank
v1 = np.array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = np.array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


# flatten of matrix

In [29]:
# create a 2x3 matrix
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 7],
                   [6,5,8]])

result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 7 6 5 8]


# set operation in numpy

In [ ]:
# union
# Intersection
# setdiffrence

In [33]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])
# union of two arrays
result = np.union1d(A, B)
print(result)  

[0 1 2 3 5]


In [31]:
# intersection of two arrays
result = np.intersect1d(A, B)
print(result) 

[3]


In [32]:
# difference of two arrays
result = np.setdiff1d(A,B)
print(result)

[1 5]


# Generting random numbers

In [34]:
# generate random integer from 0 to 9
random_number = np.random.randint(0, 10)
print(random_number)

9


In [37]:
random_number = np.random.randint(100, 1000)
print(random_number)

204


In [38]:
# generate 1D array of 5 random integers between 0 and 9
integer_array = np.random.randint(0, 10, 5)
print(integer_array)

[9 1 4 8 5]


In [43]:
# generate 2D array of shape (3, 4) with random integers
result = np.random.randint(0, 10, (4,4))
print("2D Random Integer Array:\n",result)

2D Random Integer Array:
 [[0 2 2 5]
 [1 3 3 9]
 [0 9 4 0]
 [7 2 9 5]]


In [41]:
# create an array of integers from 1 to 5
array1 = np.array([1, 2, 3, 4, 5])
# choose a random number from array1
random_choice = np.random.choice(array1)
print(random_choice)

2


In [42]:
# generate random float-point number between 0 and 1
random_number = np.random.rand(5)
print(random_number)

[0.10865375 0.12766305 0.21251601 0.43022733 0.13446991]


# NumPy Interpolation

In [48]:
np.random.seed(10)
np.random.binomial(8,0.80,size = 5)

array([6, 8, 6, 6, 7])

In [50]:
day = np.array([2, 4, 7])
gold_price = np.array([55, 58, 65])

# find the value of gold on day 3
day3_value = np.interp(5, day, gold_price)

print("The value of gold on day 5 is", day3_value)

The value of gold on day 5 is 60.333333333333336


# numpy date and time

In [53]:
# use datetime64() for different time units
year = np.datetime64('2023', 'Y')
month = np.datetime64('2023-04', 'M')
day = np.datetime64('2023-04-29', 'D')
hour = np.datetime64('2023-04-29T10', 'h')
minute = np.datetime64('2023-04-29T10:30', 'm')
second = np.datetime64('2023-04-29T10:30:15', 's')
print(type(second))
print("Year: ", year)
print("Month: ", month)
print("Day: ", day)
print("Hour: ", hour)
print("Minute: ", minute)
print("Second: ", second)

<class 'numpy.datetime64'>
Year:  2023
Month:  2023-04
Day:  2023-04-29
Hour:  2023-04-29T10
Minute:  2023-04-29T10:30
Second:  2023-04-29T10:30:15


In [54]:
from datetime import datetime

# create a datetime64 object
dt64 = np.datetime64('2023-04-29T12:34:56')

# convert datetime64 to datetime object
dt = dt64.astype(datetime)

# print the datetime object
print(type(dt))

<class 'datetime.datetime'>


In [55]:
# create a range of dates from 2023-04-01 to 2023-04-10
dates = np.arange('2023-04-01', '2023-05-11', dtype='datetime64[D]')
# print the dates
print(dates)

['2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30'
 '2023-05-01' '2023-05-02' '2023-05-03' '2023-05-04' '2023-05-05'
 '2023-05-06' '2023-05-07' '2023-05-08' '2023-05-09' '2023-05-10']


In [57]:
# create a datetime64 object for today
today = np.datetime64('today')
# add one day to today's date
tomorrow = today + np.timedelta64(1, 'D')
# create datetime64 objects for two dates
date1 = np.datetime64('2023-05-01')
date2 = np.datetime64('2023-04-01')
# calculate the number of days between the two dates
num_days = date1 - date2
# display the results
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)
print("Number of days between", date1, "and", date2, "is", num_days)

Today's date: 2023-12-04
Tomorrow's date: 2023-12-05
Number of days between 2023-05-01 and 2023-04-01 is 30 days


In [58]:
# create datetime64 objects for two dates
date1 = np.datetime64('2023-04-01')
date2 = np.datetime64('2023-05-01')
# calculate the number of business days between the two dates
num_business_days = np.busday_count(date1, date2)
# display the number of business days between the two dates
print("Number of business days between", date1, "and", date2, "is", num_business_days)

Number of business days between 2023-04-01 and 2023-05-01 is 20


# numpy file I/O

In [59]:
array1 = np.array([[2, 4, 6], 
                  [8, 10, 12]])
# save the array to a file
np.save('file1.npy', array1)


In [60]:
# load the saved NumPy array
loaded_array = np.load('file1.npy')
# display the loaded array
print(loaded_array)

[[ 2  4  6]
 [ 8 10 12]]


In [64]:
# create two NumPy arrays
array1 = np.array([2, 6, 10])
array2 = np.array([4, 8, 12])

# save the two arrays into a single file
np.savez('file2.npz', file1 = array1, file2 = dates)


In [65]:
# load the saved arrays 
load_data = np.load('file2.npz')

# retrieve the arrays using their names
# array1 = load_data['file1']
array2 = load_data['file2']

# display the loaded arrays
print(array2)

['2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30'
 '2023-05-01' '2023-05-02' '2023-05-03' '2023-05-04' '2023-05-05'
 '2023-05-06' '2023-05-07' '2023-05-08' '2023-05-09' '2023-05-10']
